=== laoqianlaile/net-hall/src/main/java/trans/trans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="trans">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="tran"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tran">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="comps"/>
      </xs:sequence>
      <xs:attribute name="extCall" use="optional" type="xs:string"/>
      <xs:attribute name="tranCode" use="required" type="xs:string"/>
      <xs:attribute name="tranName" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="comps">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="comp"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="comp">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="sql"/>
        <xs:element minOccurs="0" ref="inParams"/>
        <xs:element minOccurs="0" ref="outParams"/>
      </xs:sequence>
      <xs:attribute name="compCode" use="required" type="xs:string"/>
      <xs:attribute name="compName" use="required" type="xs:string"/>
      <xs:attribute name="expression" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sql">
    <xs:complexType mixed="true">
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="inParams">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="inParam"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="inParam">
    <xs:complexType>
      <xs:attribute name="ignoreNull" use="required" type="xs:integer"/>
      <xs:attribute name="paramCode" use="required" type="xs:string"/>
      <xs:attribute name="paramName" use="required" type="xs:string"/>
      <xs:attribute name="paramType" use="required" type="xs:string"/>
      <xs:attribute name="paramValue" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="outParams">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="outParam"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="outParam">
    <xs:complexType>
      <xs:attribute name="ignoreNull" use="required" type="xs:integer"/>
      <xs:attribute name="paramCode" use="required" type="xs:string"/>
      <xs:attribute name="paramName" use="required" type="xs:string"/>
      <xs:attribute name="paramType" use="required" type="xs:string"/>
      <xs:attribute name="paramValue" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranZFMMZH01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranZFMMZH01" tranName="支付密码找回">
        <comps>
            <comp compCode="CompZFMMZH01" compName="支付密码找回" expression="">
                <inParams>
                	<inParam ignoreNull="1" paramCode="yzfmm" paramName="原支付密码" paramType="string(0,-1)" paramValue="yzfmm"/>
                    <inParam ignoreNull="0" paramCode="xzfmm" paramName="新支付密码" paramType="string(0,-1)" paramValue="xzfmm"/>
                	<inParam ignoreNull="0" paramCode="qrxzfmm" paramName="确认新支付密码" paramType="string(0,-1)" paramValue="qrxzfmm"/>
                </inParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dw/TranXHTQ01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranXHTQ01" tranName="销户提取">
        <comps>
            <comp compCode="CompXHTQ01" compName="计算提取金额" expression="#flag=='jstqje'">
                <inParams>
                    <inParam paramCode="grzh" ignoreNull="0" paramName="个人账号" paramValue="#getUserExtInfo('grzh')" paramType="string(1,20)"/>
                    <inParam paramCode="tqyy" ignoreNull="1" paramName="提取原因" paramValue="tqyy" paramType="string(0,-1)"/>
                </inParams>
                <outParams>
                    <outParam paramCode="tqlx" ignoreNull="1" paramName="提取利息" paramValue="tqlx" paramType="double(18,2)"/>
                    <outParam paramCode="tqje" ignoreNull="1" paramName="提取金额" paramValue="tqje" paramType="double(18,2)"/>
                </outParams>
            </comp>
        	<comp compCode="CompXHTQ02" compName="销户提取提交" expression="#flag=='tjxx'">
                <inParams>
                    <inParam ignoreNull="0" paramCode="grzh" paramName="个人账号" paramType="string(0,-1)" paramValue="grzh"/>
                    <inParam ignoreNull="0" paramCode="grzhzt" paramName="个人账户状态" paramType="string(0,-1)" paramValue="grzhzt"/>
                    <inParam ignoreNull="0" paramCode="hjbz" paramName="户籍标志" paramType="string(0,-1)" paramValue="hjbz"/>
                    <inParam ignoreNull="0" paramCode="zhye" paramName="账户余额" paramType="string(0,-1)" paramValue="zhye"/>
                    <inParam ignoreNull="0" paramCode="sjhm" paramName="手机号码" paramType="string(0,-1)" paramValue="sjhm"/>
                    <inParam ignoreNull="0" paramCode="sfydk" paramName="是否有贷款" paramType="string(0,-1)" paramValue="sfydk"/>
                    <inParam ignoreNull="0" paramCode="ssjg" paramName="所属机构" paramType="string(0,-1)" paramValue="ssjg"/>
                    <inParam ignoreNull="0" paramCode="dwzh" paramName="单位账号" paramType="string(0,-1)" paramValue="dwzh"/>
                    <inParam ignoreNull="0" paramCode="dwmc" paramName="单位名称" paramType="string(0,-1)" paramValue="dwmc"/>
                    <inParam ignoreNull="0" paramCode="tqyy" paramName="提取原因" paramType="string(0,-1)" paramValue="tqyy"/>
                    <inParam ignoreNull="0" paramCode="sctqrq" paramName="上次提取日期" paramType="string(0,-1)" paramValue="sctqrq"/>
                    <inParam ignoreNull="0" paramCode="jsfs" paramName="结算方式" paramType="string(0,-1)" paramValue="jsfs"/>
                    <inParam ignoreNull="0" paramCode="skrkhyh" paramName="收款人开户银行" paramType="string(0,-1)" paramValue="skrkhyh"/>
                    <inParam ignoreNull="0" paramCode="skryhzh" paramName="收款人银行账号" paramType="string(0,-1)" paramValue="skryhzh"/>
                    <inParam ignoreNull="0" paramCode="skrzhmc" paramName="收款人账户名称" paramType="string(0,-1)" paramValue="skrzhmc"/>
                    <inParam ignoreNull="0" paramCode="tqje" paramName="提取金额" paramValue="tqje" paramType="double(18,2)" />
                    <inParam ignoreNull="0" paramCode="jymm" paramName="交易密码" paramType="string(0,-1)" paramValue="jymm"/>
                </inParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranDKJDCX.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranDKJDCX" tranName="贷款进度查询">
        <comps>
            <comp compCode="CompBatchGetTransaction" compName="贷款进度查询" expression="">
                <inParams>
                    <inParam ignoreNull="1" paramCode="apiId" paramName="交易码" paramType="constant"
                             paramValue="getDKJDCX"/>
                    <inParam ignoreNull="1" paramCode="apiName" paramName="交易描述" paramType="constant"
                             paramValue="贷款进度查询"/>
                    <inParam ignoreNull="1" paramCode="fileCols" paramName="批量文件字段定义" paramType="constant"
                             paramValue="FREEUSE1:iCount,XMQP:transdate,ACCNAME1:dkzt,ACCNAME2:state"/>
                    <inParam ignoreNull="1" paramCode="fileField" paramName="下传文件字段名" paramType="constant" paramValue="file"/>
                </inParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranFLOWS.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranFLOWS" tranName="申报流程编号">
        <comps>
            <comp compCode="CompSingleTransaction" compName="申报流程编号" expression="">
                <inParams>
                    <inParam ignoreNull="1" paramCode="apiId" paramName="交易码" paramType="constant"
                             paramValue="getflows"/>
                    <inParam ignoreNull="1" paramCode="apiName" paramName="交易描述" paramType="constant"
                             paramValue="申报流程编号"/>

                </inParams>
                <outParams>
                    <outParam ignoreNull="1" paramCode="basenum" paramName="缴存基数" paramType="string(0,-1)"
                              paramValue="jcjs"/>
                    <outParam ignoreNull="1" paramCode="iprop" paramName="个人缴存比例" paramType="string(0,-1)"
                              paramValue="iprop"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranGRXXBG01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranGRXXBG01" tranName="个人基本信息变更">
        <comps>
            <comp compCode="CompGRXXBG01" compName="获取个人基本信息" expression="#flag=='hqgrxx'">
            	<inParams>
            		<inParam paramCode="grzh" ignoreNull="1" paramName="个人账号" paramValue="grzh" paramType="string(0,-1)"/>
            	</inParams>
                <outParams>
                	<outParam ignoreNull="1" paramCode="xingbie" paramName="性别" paramType="string(0,-1)" paramValue="xingbie" />
                	<outParam ignoreNull="1" paramCode="hj" paramName="户籍" paramType="string(0,-1)" paramValue="hj" />
                	<outParam ignoreNull="1" paramCode="gddhhm" paramName="固定电话号码" paramType="string(0,-1)" paramValue="gddhhm" />
                	<outParam ignoreNull="1" paramCode="csny" paramName="出生年月" paramType="string(0,-1)" paramValue="csny" />
                	<outParam ignoreNull="1" paramCode="hyzk" paramName="婚姻状况" paramType="string(0,-1)" paramValue="hyzk" />
                	<outParam ignoreNull="1" paramCode="zhiye" paramName="职业" paramType="string(0,-1)" paramValue="zhiye" />
                	<outParam ignoreNull="1" paramCode="zhichen" paramName="职称" paramType="string(0,-1)" paramValue="zhichen" />
                	<outParam ignoreNull="1" paramCode="zhiwu" paramName="职务" paramType="string(0,-1)" paramValue="zhiwu" />
                	<outParam ignoreNull="1" paramCode="xueli" paramName="学历" paramType="string(0,-1)" paramValue="xueli" />
                	<outParam ignoreNull="1" paramCode="yzbm" paramName="邮政编码" paramType="string(0,-1)" paramValue="yzbm" />
                	<outParam ignoreNull="1" paramCode="jtzz" paramName="家庭住址" paramType="string(0,-1)" paramValue="jtzz" />
                	<outParam ignoreNull="1" paramCode="jtysr" paramName="家庭月收入" paramType="string(0,-1)" paramValue="jtysr" />
                	<outParam ignoreNull="1" paramCode="xingming" paramName="姓名" paramType="string(0,-1)" paramValue="xingming" />
                	<outParam ignoreNull="1" paramCode="zjlx" paramName="证件类型" paramType="string(0,-1)" paramValue="zjlx" />
                	<outParam ignoreNull="1" paramCode="zjhm" paramName="证件号码" paramType="string(0,-1)" paramValue="zjhm" />
                	<outParam ignoreNull="1" paramCode="sjhm" paramName="手机号码" paramType="string(0,-1)" paramValue="sjhm" />
					<!--ish04新增-->
					<outParam ignoreNull="1" paramCode="grjcjs" paramName="个人缴存基数" paramType="string(0,-1)" paramValue="grjcjs" />
                </outParams>
            </comp>
            <comp compCode="CompGRXXBG02" compName="提交个人基本信息" expression="#flag=='tjgrxx'">
                <inParams>
               		<inParam ignoreNull="1" paramCode="grzh" paramName="个人账号" paramType="string(1,30)" paramValue="grzh"/>
               		<inParam ignoreNull="1" paramCode="hj" paramName="户籍地" paramType="string(0,-1)" paramValue="hj" />
                	<inParam ignoreNull="1" paramCode="gddhhm" paramName="固定电话号码" paramType="string(0,-1)" paramValue="gddhhm" />
                	<inParam ignoreNull="1" paramCode="zhiye" paramName="职业" paramType="string(0,-1)" paramValue="zhiye" />
                	<inParam ignoreNull="1" paramCode="zhichen" paramName="职称" paramType="string(0,-1)" paramValue="zhichen" />
                	<inParam ignoreNull="1" paramCode="zhiwu" paramName="职务" paramType="string(0,-1)" paramValue="zhiwu" />
                	<inParam ignoreNull="1" paramCode="xueli" paramName="学历" paramType="string(0,-1)" paramValue="xueli" />
                	<inParam ignoreNull="1" paramCode="yzbm" paramName="邮政编码" paramType="string(0,-1)" paramValue="yzbm" />
                	<inParam ignoreNull="1" paramCode="jtzz" paramName="家庭住址" paramType="string(0,-1)" paramValue="jtzz" />
                	<inParam ignoreNull="1" paramCode="jtysr" paramName="家庭月收入" paramType="string(0,-1)" paramValue="jtysr" />
                </inParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranZHMXXX01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranZHMXXX01" tranName="公积金账户明细信息">
        <comps>
            <comp compCode="CompBatchGetTransaction" compName="获取公积金账户明细信息" expression="">
                <inParams>
                    <inParam ignoreNull="1" paramCode="apiId" paramName="交易码" paramType="constant"
                             paramValue="getsgGrmxxx"/>
                    <inParam ignoreNull="1" paramCode="apiName" paramName="交易描述" paramType="constant"
                             paramValue="个人明细查询"/>
                    <inParam ignoreNull="1" paramCode="fileCols" paramName="批量文件字段定义" paramType="constant"
                             paramValue="seqno:hh,accnum1:jyrq,accname1:grzh,unitaccname2:xm,payvounum:ywlx,unitaccname1:fse,JTZZ:ye,unitaccnum2:ksny,REASON:zzny,AGENTOP:bz,XMQP:rzzt,ACCNUM2:jbr"/>
                    <inParam ignoreNull="1" paramCode="fileField" paramName="下传文件字段名" paramType="constant" paramValue="file"/>
                </inParams>
                <outParams>
                    <outParam ignoreNull="1" paramCode="basenum" paramName="缴存基数" paramType="string(0,-1)"
                              paramValue="jcjs"/>
                    <outParam ignoreNull="1" paramCode="iprop" paramName="个人缴存比例" paramType="string(0,-1)"
                              paramValue="iprop"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranGRJCXX01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranGRJCXX01" tranName="获取个人缴存信息">
        <comps>
            <comp compCode="CompGRJCXX01" compName="获取个人缴存信息" expression="#taskFlag=='queryGRJCXX'">
                <inParams>
                    <inParam ignoreNull="0" paramCode="grzh" paramName="个人账号" paramType="string(1,20)" paramValue="grzh"/>
                </inParams>
                <outParams>
                    <outParam ignoreNull="1" paramCode="xingming" paramName="姓名" paramValue="xingming" paramType="string(0,80)" ></outParam>
                    <outParam ignoreNull="1" paramCode="grjcjs" paramName="个人缴存基数" paramValue="grjcjs" paramType="string(0,-1)" ></outParam>
                    <outParam ignoreNull="1" paramCode="yjce" paramName="月缴存额" paramValue="yjce" paramType="string(0,-1)" ></outParam>
                    <outParam ignoreNull="1" paramCode="zjhm" paramName="证件号码" paramValue="zjhm" paramType="string(0,20)" ></outParam>
                    <outParam ignoreNull="1" paramCode="zjlx" paramName="证件类型" paramValue="zjlx" paramType="string(0,2)" ></outParam>
                    <outParam ignoreNull="1" paramCode="dwyjce" paramName="单位月缴存额" paramValue="dwyjce" paramType="string(0,-1)" ></outParam>
                    <outParam ignoreNull="1" paramCode="gryjce" paramName="个人月缴存额" paramValue="gryjce" paramType="string(0,-1)" ></outParam>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/common/yhzc/TranGRZC.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../trans.xsd">
    <tran tranCode="TranGRZC" tranName="个人注册">
        <comps>
            <comp compCode="CompGRZC201" compName="用户注册" expression="">
                <inParams>
                    <inParam ignoreNull="0" paramCode="loginId" paramName="登录id" paramType="string(0,25)" paramValue="zjhm"/>
                    <inParam ignoreNull="0" paramCode="zjhm" paramName="身份证号" paramType="string(0,20)" paramValue="zjhm"/>
                    <inParam ignoreNull="0" paramCode="sjhm" paramName="身份证号" paramType="string(0,20)" paramValue="sjhm"/>
                    <inParam ignoreNull="0" paramCode="zdyyhm" paramName="身份证号" paramType="string(0,20)" paramValue="zjhm"/>
                    <inParam ignoreNull="0" paramCode="xingming" paramName="身份证号" paramType="string(0,20)" paramValue="xingming"/>
                    <inParam ignoreNull="0" paramCode="zjlx" paramName="身份证号" paramType="string(0,20)" paramValue="zjlx"/>
                    <inParam ignoreNull="0" paramCode="dxyzm" paramName="身份证号" paramType="string(0,20)" paramValue="yzm"/>
                    <inParam ignoreNull="0" paramCode="pwd" paramName="身份证号" paramType="string(0,20)" paramValue="gjjmm"/>
                    <inParam ignoreNull="0" paramCode="password" paramName="姓名" paramType="string(0,32)" paramValue="gjjmm"/>
                </inParams>
                <outParams>
                    <outParam ignoreNull="0" paramCode="grzh" paramName="个人账号" paramType="string(0,-1)" paramValue="grzh"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>
