=== laoqianlaile/net-hall/src/main/java/trans/trans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="trans">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="tran"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tran">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="comps"/>
      </xs:sequence>
      <xs:attribute name="extCall" use="optional" type="xs:string"/>
      <xs:attribute name="tranCode" use="required" type="xs:string"/>
      <xs:attribute name="tranName" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="comps">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="comp"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="comp">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="sql"/>
        <xs:element minOccurs="0" ref="inParams"/>
        <xs:element minOccurs="0" ref="outParams"/>
      </xs:sequence>
      <xs:attribute name="compCode" use="required" type="xs:string"/>
      <xs:attribute name="compName" use="required" type="xs:string"/>
      <xs:attribute name="expression" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sql">
    <xs:complexType mixed="true">
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="inParams">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="inParam"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="inParam">
    <xs:complexType>
      <xs:attribute name="ignoreNull" use="required" type="xs:integer"/>
      <xs:attribute name="paramCode" use="required" type="xs:string"/>
      <xs:attribute name="paramName" use="required" type="xs:string"/>
      <xs:attribute name="paramType" use="required" type="xs:string"/>
      <xs:attribute name="paramValue" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="outParams">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="outParam"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="outParam">
    <xs:complexType>
      <xs:attribute name="ignoreNull" use="required" type="xs:integer"/>
      <xs:attribute name="paramCode" use="required" type="xs:string"/>
      <xs:attribute name="paramName" use="required" type="xs:string"/>
      <xs:attribute name="paramType" use="required" type="xs:string"/>
      <xs:attribute name="paramValue" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== laoqianlaile/net-hall/src/main/java/trans/ln/TranDKXXCX01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranDKXXCX01" tranName="贷款信息查询">
        <comps>
            <comp compCode="CompXMCX02" compName="获取项目列表" expression="#flag=='instep1'">
                <inParams>
                    <inParam ignoreNull="1" paramCode="kfsdjh" paramName="开发商登记号" paramType="string(1,20)" paramValue="kfsdjh"/>
                    <inParam ignoreNull="1" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
                </inParams>
            </comp>
            <comp compCode="CompDKXXCX01" compName="获取项目下贷款信息" expression="#flag=='getdkxx'">
                <inParams>
                    <inParam ignoreNull="1" paramCode="xmxyh" paramName="项目协议号" paramType="string(1,20)" paramValue="xmxyh"/>
                    <inParam ignoreNull="1" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
                </inParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranTJGRQF01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranTJGRQF01" tranName="提交启封信息">
        <comps>
        	<comp compCode="CompTJGRQF01" compName="提交启封信息" expression="">
                <inParams>
                    <inParam ignoreNull="0" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
                    <inParam ignoreNull="0" paramCode="operid" paramName="操作员id" paramType="string(1,30)" paramValue="_OPERID"/>
                </inParams>
                <outParams>
                    <outParam ignoreNull="0" paramCode="zxjg" paramName="定时任务执行结果" paramValue="zxjg" paramType="string(0,-1)" ></outParam>
                    <outParam ignoreNull="0" paramCode="jgms" paramName="结果描述" paramValue="jgms" paramType="string(0,-1)" ></outParam>
           	   		<!--启用凭证系统时设置此出口参数  -->
               		<outParam ignoreNull="1" paramCode="filename" paramName="凭证文件名" paramType="string(0,-1)" paramValue="filename"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranMMBG01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranMMBG01" tranName="个人密码修改">
        <comps>
            <comp compCode="CompMMBG01" compName="个人密码修改" expression="">
                <inParams>
               		<inParam ignoreNull="0" paramCode="accnum" paramName="个人账号" paramType="string(1,30)" paramValue="accnum"/>
               		<inParam ignoreNull="0" paramCode="certinum" paramName="证件号码" paramType="string(1,30)" paramValue="certinum"/>
               		<inParam ignoreNull="0" paramCode="oppwd" paramName="柜员密码" paramType="string(1,30)" paramValue="oppwd"/>
               		<inParam ignoreNull="0" paramCode="pwd" paramName="密码" paramType="string(1,30)" paramValue="pwd"/>
                </inParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/ln/TranHQDKXX01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranHQDKXX01" tranName="获取贷款信息">
        <comps>
            <comp compCode="CompHQDKXX01" compName="获取贷款信息" expression="">
                <inParams>
					<inParam ignoreNull="1" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
                	<inParam ignoreNull="1" paramCode="jkhtbh" paramName="借款合同编号" paramType="string(1,30)" paramValue="jkhtbh"/>
					<inParam ignoreNull="1" paramCode="jkhtbhsz" paramName="借款合同编号数组" paramType="string(0,-1)" paramValue="jkhtbhsz"/>
                </inParams>
                <outParams>
                	<outParam ignoreNull="1" paramCode="jgmc" paramName="机构名称" paramType="string(0,-1)" paramValue="jgmc"/>
                	<outParam ignoreNull="1" paramCode="swtyhmc" paramName="受委托银行名称" paramType="string(0,-1)" paramValue="swtyhmc"/>
                	<outParam ignoreNull="1" paramCode="jkrxm" paramName="借款人姓名" paramType="string(0,-1)" paramValue="jkrxm"/>
                	<outParam ignoreNull="1" paramCode="jkrzjhm" paramName="借款人证件号码" paramType="string(0,-1)" paramValue="jkrzjhm"/>
                	<outParam ignoreNull="1" paramCode="dkffrq" paramName="贷款发放日期" paramType="string(0,-1)" paramValue="dkffrq"/>
                	<outParam ignoreNull="1" paramCode="dkffe" paramName="贷款发放额" paramType="string(0,-1)" paramValue="dkffe"/>
                	<outParam ignoreNull="1" paramCode="dkqs" paramName="贷款期数" paramType="string(0,-1)" paramValue="dkqs"/>
                	<outParam ignoreNull="1" paramCode="ydhkr" paramName="约定还款日" paramType="string(0,-1)" paramValue="ydhkr"/>
                	<outParam ignoreNull="1" paramCode="dkhkfs" paramName="贷款还款方式" paramType="string(0,-1)" paramValue="dkhkfs"/>
                	<outParam ignoreNull="1" paramCode="yhke" paramName="月还款额" paramType="string(0,-1)" paramValue="yhke"/>
                	<outParam ignoreNull="1" paramCode="hkzh" paramName="还款账号" paramType="string(0,-1)" paramValue="hkzh"/>
                	<outParam ignoreNull="1" paramCode="htzt" paramName="合同状态" paramType="string(0,-1)" paramValue="htzt"/>
                	<outParam ignoreNull="1" paramCode="dkye" paramName="贷款余额" paramType="string(0,-1)" paramValue="dkye"/>
                	<outParam ignoreNull="1" paramCode="dkll" paramName="贷款利率" paramType="string(0,-1)" paramValue="dkll"/>
                	<outParam ignoreNull="1" paramCode="sfyq" paramName="是否逾期" paramType="string(0,-1)" paramValue="sfyq"/>
                	<outParam ignoreNull="1" paramCode="yqbjze" paramName="逾期本金总额" paramType="string(0,-1)" paramValue="yqbjze"/>
                	<outParam ignoreNull="1" paramCode="yqlxze" paramName="逾期利息总额" paramType="string(0,-1)" paramValue="yqlxze"/>
                	<outParam ignoreNull="1" paramCode="fxze" paramName="罚息总额" paramType="string(0,-1)" paramValue="fxze"/>
                	<outParam ignoreNull="1" paramCode="tqhj" paramName="拖欠合计" paramType="string(0,-1)" paramValue="tqhj"/>
                	<outParam ignoreNull="1" paramCode="dqqc" paramName="当前期次" paramType="string(0,-1)" paramValue="dqqc"/>
                	<outParam ignoreNull="1" paramCode="yddqrq" paramName="约定到期日期" paramType="string(0,-1)" paramValue="yddqrq"/>
                	<outParam ignoreNull="1" paramCode="syqs" paramName="剩余期数" paramType="string(0,-1)" paramValue="syqs"/>
                	<outParam ignoreNull="1" paramCode="xdqrq" paramName="现到期日期" paramType="string(0,-1)" paramValue="xdqrq"/>
                	<outParam ignoreNull="1" paramCode="tqqbhkje" paramName="提前全部还款金额" paramType="string(0,-1)" paramValue="tqqbhkje"/>
					<outParam ignoreNull="1" paramCode="kkrlx" paramName="扣款人类型" paramType="string(0,-1)" paramValue="kkrlx"/>
                	<outParam ignoreNull="1" paramCode="kkrxm" paramName="扣款人姓名" paramType="string(0,-1)" paramValue="kkrxm"/>
                	<outParam ignoreNull="1" paramCode="kkrzjhm" paramName="扣款人证件号码" paramType="string(0,-1)" paramValue="kkrzjhm"/>
                	<outParam ignoreNull="1" paramCode="gtjkrxm" paramName="共同借款人姓名" paramType="string(0,-1)" paramValue="gtjkrxm"/>      
                	<outParam ignoreNull="1" paramCode="zdhke" paramName="最低还款额" paramType="string(0,-1)" paramValue="zdhke"/>
					<outParam ignoreNull="1" paramCode="dkzxll" paramName="贷款执行利率" paramType="string(0,-1)" paramValue="dkzxll"/>
					<outParam ignoreNull="1" paramCode="htdkje" paramName="合同贷款金额" paramType="string(0,-1)" paramValue="htdkje"/>
					<outParam ignoreNull="1" paramCode="yqbj" paramName="逾期本金" paramType="string(0,-1)" paramValue="yqbj"/>
					<outParam ignoreNull="1" paramCode="yqlx" paramName="逾期利息" paramType="string(0,-1)" paramValue="yqlx"/>
					<outParam ignoreNull="1" paramCode="whfx" paramName="未还罚息" paramType="string(0,-1)" paramValue="whfx"/>
					<outParam ignoreNull="1" paramCode="yqzje" paramName="逾期总金额" paramType="string(0,-1)" paramValue="yqzje"/>
					<outParam ignoreNull="1" paramCode="xcslx" paramName="新产生利息" paramType="string(0,-1)" paramValue="xcslx"/>
					<outParam ignoreNull="1" paramCode="wdqbj" paramName="未到期本金" paramType="string(0,-1)" paramValue="wdqbj"/>
					<!--ish04新增-->
					<outParam ignoreNull="1" paramCode="hsbjze" paramName="回收本金总额" paramType="string(0,-1)" paramValue="hsbjze"/>
				</outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dw/TranHQSBJG01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranHQSBJG01" tranName="获取申报提交到核心的指定机构">
        <comps>
			<comp compCode="CompHQSBJG01" compName="查询申报机构" expression="">
				<inParams>
					<inParam paramCode="grzh" ignoreNull="0" paramName="个人账号" paramValue="#getUserExtInfo('grzh')" paramType="string(1,20)"/>
					<inParam paramCode="ywbh" ignoreNull="0" paramName="业务编号" paramValue="ywbh" paramType="string(0,-1)"/>
					<inParam paramCode="qdbh" ignoreNull="0" paramName="渠道编号" paramValue="qdbh" paramType="string(0,-1)"/>
				</inParams>
				<outParams>
					<outParam paramCode="zdjg" ignoreNull="1" paramName="指定机构" paramValue="zdjg" paramType="string(0,-1)"/>
				</outParams>
			</comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/ln/TranXMXQ01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranXMXQ01" tranName="开发商项目新签">
        <comps>
            <comp compCode="CompXMXQ01" compName="获取开发商信息" expression="#flag=='instep1'">
            	<inParams>
            		<inParam ignoreNull="1" paramCode="kfsdjh" paramName="单位账号" paramType="string(1,20)" paramValue="kfsdjh"/>
            	</inParams>
				<outParams>
					<outParam ignoreNull="1" paramCode="kfsmc" paramName="开发商名称" paramType="string(0,-1)" paramValue="kfsmc"/>
					<outParam ignoreNull="1" paramCode="dwlx" paramName="单位类型" paramType="string(0,-1)" paramValue="dwlx"/>
					<outParam ignoreNull="1" paramCode="zcdz" paramName="注册地址" paramType="string(0,-1)" paramValue="zcdz"/>
					<outParam ignoreNull="1" paramCode="bgdz" paramName="办公地址" paramType="string(0,-1)" paramValue="bgdz"/>
					<outParam ignoreNull="1" paramCode="dwfrdbxm" paramName="单位法人代表姓名" paramType="string(0,-1)" paramValue="dwfrdbxm"/>
					<outParam ignoreNull="1" paramCode="dwfrdbzjlx" paramName="单位法人代表证件类型" paramType="string(0,-1)" paramValue="dwfrdbzjlx"/>
					<outParam ignoreNull="1" paramCode="dwfrdbzjhm" paramName="单位法人代表证件号码" paramType="string(0,-1)" paramValue="dwfrdbzjhm"/>
					<outParam ignoreNull="1" paramCode="sjhm" paramName="手机号码" paramType="string(0,-1)" paramValue="sjhm"/>
					<outParam ignoreNull="1" paramCode="dwdh" paramName="单位电话" paramType="string(0,-1)" paramValue="dwdh"/>
					<outParam ignoreNull="1" paramCode="zczb" paramName="注册资本" paramType="string(0,-1)" paramValue="zczb"/>
					<outParam ignoreNull="1" paramCode="dwslrq" paramName="单位设立日期" paramType="string(0,-1)" paramValue="dwslrq"/>
					<outParam ignoreNull="1" paramCode="kfzz" paramName="开发资质" paramType="string(0,-1)" paramValue="kfzz"/>
					<outParam ignoreNull="1" paramCode="tyshxydm" paramName="统一社会信用代码" paramType="string(0,-1)" paramValue="tyshxydm"/>
					<outParam ignoreNull="1" paramCode="jgxydm" paramName="机构信用代码" paramType="string(0,-1)" paramValue="jgxydm"/>
					<outParam ignoreNull="1" paramCode="sfsqbzj" paramName="是否收取保证金" paramType="string(0,-1)" paramValue="sfsqbzj"/>
					<outParam ignoreNull="1" paramCode="bzjbl" paramName="保证金比例" paramType="string(0,-1)" paramValue="bzjbl"/>
					<outParam ignoreNull="1" paramCode="jyfw" paramName="经营范围" paramType="string(0,-1)" paramValue="jyfw"/>
				</outParams>
            </comp>
			<comp compCode="CompXMXQ02" compName="获取协议有效时间参数" expression="#flag=='instep1'">
				<outParams>
					<outParam ignoreNull="1" paramCode="yxsj" paramName="有效时间" paramType="string(0,-1)" paramValue="yxsj"/>
				</outParams>
			</comp>
			<comp compCode="CompXMXQ03" compName="校验楼栋数据" expression="#flag=='checkldxx'">
				<inParams>
					<inParam ignoreNull="1" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
					<inParam ignoreNull="1" paramCode="lpzzs" paramName="楼盘总幢数" paramType="int" paramValue="lpzzs"/>
				</inParams>
			</comp>
			<comp compCode="CompXMXQ04" compName="校验楼盘数据" expression="#flag=='checklpxx'">
				<inParams>
					<inParam ignoreNull="1" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
					<inParam ignoreNull="1" paramCode="lpzts" paramName="楼盘总套数" paramType="int" paramValue="lpzts"/>
				</inParams>
			</comp>
			<comp compCode="CompXMXQ05" compName="提交开发商项目新签信息" expression="#flag=='outstep1'">
				<inParams>
					<inParam ignoreNull="1" paramCode="xmmc" paramName="项目名称" paramType="string(0,-1)" paramValue="xmmc"/>
					<inParam ignoreNull="1" paramCode="lpqymc" paramName="楼盘区域名称" paramType="string(0,-1)" paramValue="lpqymc"/>
					<inParam ignoreNull="1" paramCode="xmwz" paramName="项目位置" paramType="string(0,-1)" paramValue="xmwz"/>
					<inParam ignoreNull="1" paramCode="xykssj" paramName="协议开始日期" paramType="string(0,-1)" paramValue="xykssj"/>
					<inParam ignoreNull="1" paramCode="xyjssj" paramName="协议结束日期" paramType="string(0,-1)" paramValue="xyjssj"/>
					<inParam ignoreNull="1" paramCode="lpmj" paramName="楼盘面积" paramType="string(0,-1)" paramValue="lpmj"/>
					<inParam ignoreNull="1" paramCode="lpjj" paramName="楼盘均价" paramType="string(0,-1)" paramValue="lpjj"/>
					<inParam ignoreNull="1" paramCode="lpzts" paramName="楼盘总套数" paramType="string(0,-1)" paramValue="lpzts"/>
					<inParam ignoreNull="1" paramCode="lpzzs" paramName="楼盘总幢数" paramType="string(0,-1)" paramValue="lpzzs"/>
					<inParam ignoreNull="1" paramCode="yssj" paramName="预售时间" paramType="string(0,-1)" paramValue="yssj"/>
					<inParam ignoreNull="1" paramCode="jgsj" paramName="竣工时间" paramType="string(0,-1)" paramValue="jgsj"/>
					<inParam ignoreNull="1" paramCode="syqlx" paramName="使用权类型" paramType="string(0,-1)" paramValue="syqlx"/>
					<inParam ignoreNull="1" paramCode="syqzzrq" paramName="使用权终止日期" paramType="string(0,-1)" paramValue="syqzzrq"/>
					<inParam ignoreNull="1" paramCode="tdzfzjg" paramName="土地证发证机关" paramType="string(0,-1)" paramValue="tdzfzjg"/>
					<inParam ignoreNull="1" paramCode="jsydghydmj" paramName="建设用地规划用地面积" paramType="string(0,-1)" paramValue="jsydghydmj"/>
					<inParam ignoreNull="1" paramCode="jsydghjsgm" paramName="保证金建设用地规划建设规模比例" paramType="string(0,-1)" paramValue="jsydghjsgm"/>
					<inParam ignoreNull="1" paramCode="jsydghydxz" paramName="建设用地规划用地性质" paramType="string(0,-1)" paramValue="jsydghydxz"/>
					<inParam ignoreNull="1" paramCode="tdzbh" paramName="土地证编号" paramType="string(0,-1)" paramValue="tdzbh"/>
					<inParam ignoreNull="1" paramCode="jsgcsgxkz" paramName="建筑工程施工许可证" paramType="string(0,-1)" paramValue="jsgcsgxkz"/>
					<inParam ignoreNull="1" paramCode="jzgcghxkz" paramName="建筑工程规划许可证" paramType="string(0,-1)" paramValue="jzgcghxkz"/>
					<inParam ignoreNull="1" paramCode="jsydghxkz" paramName="建设用地规划许可证" paramType="string(0,-1)" paramValue="jsydghxkz"/>
					<inParam ignoreNull="1" paramCode="bzjkhyh" paramName="保证金开户银行" paramType="string(0,-1)" paramValue="bzjkhyh"/>
					<inParam ignoreNull="1" paramCode="bzjzhmc" paramName="保证金账户名称" paramType="string(0,-1)" paramValue="bzjzhmc"/>
					<inParam ignoreNull="1" paramCode="bzjzhhm" paramName="保证金账户号码" paramType="string(0,-1)" paramValue="bzjzhhm"/>
					<inParam ignoreNull="1" paramCode="jyfw" paramName="经营范围" paramType="string(0,-1)" paramValue="jyfw"/>
					<inParam ignoreNull="1" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
				</inParams>
			</comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/common/dlgl/TranDLYZ101.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../trans.xsd">
    <tran tranCode="TranDLYZ101" tranName="管理员登录验证返回用户信息">
        <comps>
        	<comp compCode="CompDLYZ101" compName="管理员登录验证返回用户信息" expression="">
                <inParams>
                    <inParam ignoreNull="0" paramCode="loginId" paramName="登录id" paramType="string(0,25)" paramValue="loginId"/>
                    <inParam ignoreNull="0" paramCode="password" paramName="密码" paramType="string(0,-1)" paramValue="password"/>
                </inParams>
                <outParams>
                	<outParam ignoreNull="0" paramCode="managerId" paramName="管理员序号" paramType="string(0,-1)" paramValue="managerId"/>
                	<outParam ignoreNull="0" paramCode="managerName" paramName="管理员名称" paramType="string(0,-1)" paramValue="managerName"/>
                	<outParam ignoreNull="0" paramCode="instcode" paramName="机构号" paramType="string(0,-1)" paramValue="instcode"/>
                	<outParam ignoreNull="0" paramCode="instname" paramName="机构名" paramType="string(0,-1)" paramValue="instname"/>
                	<outParam ignoreNull="0" paramCode="rolecodes" paramName="角色集合" paramType="string(0,-1)" paramValue="rolecodes"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/ln/TranZGEDNX01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranZGEDNX01" tranName="获取最高贷款额度年限参数">
        <comps>
            <comp compCode="CompZGEDNX01" compName="获取最高贷款额度年限参数" expression="">
                <outParams>
                	<outParam ignoreNull="1" paramCode="zgdkedfirst" paramName="最高贷款额度(一手房)" paramType="string(0,-1)" paramValue="zgdkedfirst"/>
                	<outParam ignoreNull="1" paramCode="zgdkedsecond" paramName="最高贷款额度(二手房)" paramType="string(0,-1)" paramValue="zgdkedsecond"/>
                	<outParam ignoreNull="1" paramCode="zgdknx" paramName="最高贷款年限" paramType="string(0,-1)" paramValue="zgdknx"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>
