=== laoqianlaile/net-hall/src/main/java/trans/trans.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="trans">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="tran"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="tran">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="comps"/>
      </xs:sequence>
      <xs:attribute name="extCall" use="optional" type="xs:string"/>
      <xs:attribute name="tranCode" use="required" type="xs:string"/>
      <xs:attribute name="tranName" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="comps">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="comp"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="comp">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" ref="sql"/>
        <xs:element minOccurs="0" ref="inParams"/>
        <xs:element minOccurs="0" ref="outParams"/>
      </xs:sequence>
      <xs:attribute name="compCode" use="required" type="xs:string"/>
      <xs:attribute name="compName" use="required" type="xs:string"/>
      <xs:attribute name="expression" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="sql">
    <xs:complexType mixed="true">
      <xs:attribute name="id" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="inParams">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="inParam"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="inParam">
    <xs:complexType>
      <xs:attribute name="ignoreNull" use="required" type="xs:integer"/>
      <xs:attribute name="paramCode" use="required" type="xs:string"/>
      <xs:attribute name="paramName" use="required" type="xs:string"/>
      <xs:attribute name="paramType" use="required" type="xs:string"/>
      <xs:attribute name="paramValue" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="outParams">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="outParam"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="outParam">
    <xs:complexType>
      <xs:attribute name="ignoreNull" use="required" type="xs:integer"/>
      <xs:attribute name="paramCode" use="required" type="xs:string"/>
      <xs:attribute name="paramName" use="required" type="xs:string"/>
      <xs:attribute name="paramType" use="required" type="xs:string"/>
      <xs:attribute name="paramValue" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranJCJSTZ01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranJCJSTZ01" tranName="缴存基数调整">
        <comps>
        	 <comp compCode="CompJCJSTZ01" compName="获取缴存基数调低标志" expression="#flag=='hqtdflag'">
            	 <inParams>
               		<inParam ignoreNull="0" paramCode="dwzh" paramName="单位账号" paramType="string(1,30)" paramValue="dwzh"/>
                </inParams>
                <outParams>
                	<outParam paramCode="tdflag" ignoreNull="0" paramName="缴存基数调低标志" paramValue="tdflag" paramType="string(0,-1)"/>
                </outParams>
            </comp>
      	   <comp compCode="CompJCJSTZ02" compName="校验提交信息" expression="#flag=='jyxx'">
            	 <inParams>
               		<inParam ignoreNull="0" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
                </inParams>
            </comp>
            <comp compCode="CompJCJSTZ03" compName="提交缴存基数调整信息" expression="#flag=='tjxx'">
                <inParams>
               		<inParam ignoreNull="0" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
               		<inParam ignoreNull="0" paramCode="dwzh" paramName="单位账号" paramType="string(1,30)" paramValue="dwzh"/>
                </inParams>
                <outParams>
                	<!--启用凭证系统时设置此出口参数  -->
               		<outParam ignoreNull="1" paramCode="filename" paramName="凭证文件名" paramType="string(0,-1)" paramValue="filename"/>
                </outParams>
            </comp>
             <comp compCode="CompJCJSTZ04" compName="获取月缴存额" expression="#flag=='hqyjce'">
            	 <inParams>
               		<inParam ignoreNull="0" paramCode="grzh" paramName="个人账号" paramType="string(0,-1)" paramValue="grzh"/>
               		<inParam ignoreNull="0" paramCode="tzhgrjcjs" paramName="调整后个人缴存基数" paramType="string(0,-1)" paramValue="tzhgrjcjs"/>
                </inParams>
                  <outParams>
               		<outParam ignoreNull="0" paramCode="tzdwyjce" paramName="调整后单位月缴存额" paramType="string(0,-1)" paramValue="tzdwyjce"/>
               		<outParam ignoreNull="0" paramCode="tzgryjce" paramName="调整后个人月缴存额" paramType="string(0,-1)" paramValue="tzgryjce"/>
               		<outParam ignoreNull="0" paramCode="tzhyjce" paramName="调整后月缴存额" paramType="string(0,-1)" paramValue="tzhyjce"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranGRFCXXSC2.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranGRFCXXSC2" tranName="职工封存">
        <comps>
            <comp compCode="CompBatchPostTransaction" compName="职工封存" expression="">
                <inParams>
                    <inParam ignoreNull="1" paramCode="apiId" paramName="交易码" paramType="constant"
                             paramValue="upGRFCXXSC2"/>
                    <inParam ignoreNull="1" paramCode="apiName" paramName="交易描述" paramType="constant"
                             paramValue="职工封存"/>
                    <inParam ignoreNull="1" paramCode="fileCols" paramName="批量文件字段定义" paramType="constant"
                             paramValue="dp077:dp077,GRZH:accnum1,XINGMING:accname1,ZJHM:accnum2,SEQNO:seqno,GRJCJS:amt1,AMT1:amt2,AMT2:unitprop,JZNY:freeuse1,PAYVOUAMT:freeuse2,INSTANCE:instance,DPBUSITYPE:dpbusitype,DWZH:unitaccnum1,TRANSDATE:transdate,AGENTINSTCODE:unitaccname1,AGENTOP:unitaccname2,PROPTYPE:payvounum"/>
                    <inParam ignoreNull="1" paramCode="fileField" paramName="上传文件字段名" paramType="constant"
                             paramValue="file"/>
                    <inParam ignoreNull="1" paramCode="batchDataListId" paramName="批量列表id" paramType="constant"
                             paramValue="grqfList"/>
                </inParams>

            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranMMBG.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranMMBG" tranName="个人密码变更">
        <comps>
            <comp compCode="CompSingleTransaction" compName="个人密码变更" expression="">
                <inParams>
                    <inParam ignoreNull="1" paramCode="apiId" paramName="交易码" paramType="constant"
                             paramValue="getGRMMBG"/>
                    <inParam ignoreNull="1" paramCode="apiName" paramName="交易描述" paramType="constant"
                             paramValue="个人密码变更"/>
                </inParams>
                <outParams>
                    <outParam ignoreNull="1" paramCode="uprop" paramName="缴存基数" paramType="string(0,-1)" paramValue="uprop"/>
                    <outParam ignoreNull="1" paramCode="unitprop" paramName="缴存基数" paramType="string(0,-1)" paramValue="unitprop"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dw/TranZXBJ1.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranZXBJ1" tranName="在线补缴">
        <comps>
            <comp compCode="CompBatchPostTransaction" compName="在线补缴" expression="">
                <inParams>
                    <inParam ignoreNull="1" paramCode="apiId" paramName="交易码" paramType="constant"
                             paramValue="getBJDJ1"/>
                    <inParam ignoreNull="1" paramCode="apiName" paramName="交易描述" paramType="constant"
                             paramValue="在线补缴"/>
                    <inParam ignoreNull="1" paramCode="fileCols" paramName="批量文件字段定义" paramType="constant"
                             paramValue="dp077:dp077,GRZH:unitaccnum1,XINGMING:unitaccname1,ZJHM:unitaccnum2,AMT1:amt1,BEGYM:accnum1,ENDYM:accnum2,DWZH:accname1,TRANSDATE:transdate,AGENTINSTCODE:agentinstcode,AGENTOP:agentop,DPBUSITYPE:dpbusitype,SEQNO:seqno,INSTANCE:instance,FREEUSE1:freeuse1,AMT2:amt2,PAYVOUAMT:payvouamt,REASON:reason"/>
                    <inParam ignoreNull="1" paramCode="fileField" paramName="上传文件字段名" paramType="constant"
                             paramValue="file"/>
                    <inParam ignoreNull="1" paramCode="batchDataListId" paramName="批量列表id" paramType="constant"
                             paramValue="datalist1"/>
                </inParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranLoanProgress.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranLoanProgress" tranName="贷款进度查询">
        <comps>
        	<comp compCode="CompBatchGetTransaction" compName="贷款进度查询" expression="">
                <inParams>
                    <inParam ignoreNull="1" paramCode="apiId" paramName="交易码" paramType="constant"
                             paramValue="getLoanProgress"/>
                    <inParam ignoreNull="1" paramCode="apiName" paramName="交易描述" paramType="constant"
                             paramValue="贷款进度查询"/>
                    <inParam ignoreNull="1" paramCode="fileCols" paramName="批量文件字段定义" paramType="constant"
                             paramValue="FREEUSE1:iCount,ACCNAME2:dkyjh,UNITACCNAME1:xingming,XMQP:transdate,ACCNAME1:dkzt"/>
                    <inParam ignoreNull="1" paramCode="fileField" paramName="下传文件字段名" paramType="constant" paramValue="file"/>
                </inParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dp/TranHQDWXX01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranHQDWXX01" tranName="获取单位信息">
        <comps>
        	<comp compCode="CompHQDWXX01" compName="获取单位信息" expression="">
                <inParams>
                    <inParam ignoreNull="0" paramCode="instance" paramName="实例号" paramType="int" paramValue="_IS"/>
                </inParams>
                <outParams>
                    <outParam ignoreNull="1" paramCode="dwjcbl" paramName="单位缴存比例" paramType="string(0,-1)" paramValue="dwjcbl"/>
                    <outParam ignoreNull="1" paramCode="grjcbl" paramName="个人缴存比例" paramType="string(0,-1)" paramValue="grjcbl"/>
                    <outParam ignoreNull="1" paramCode="dwfcrs" paramName="单位封存人数" paramType="string(0,-1)" paramValue="dwfcrs"/>
                    <outParam ignoreNull="1" paramCode="dwmc" paramName="单位名称" paramType="string(0,-1)" paramValue="dwmc"/>
                    <outParam ignoreNull="1" paramCode="tyshxydm" paramName="统一社会信用代码" paramType="string(0,-1)" paramValue="tyshxydm"/>
                    <outParam ignoreNull="1" paramCode="zzjgdm" paramName="组织机构代码" paramType="string(0,-1)" paramValue="zzjgdm"/>
                    <outParam ignoreNull="1" paramCode="dwdz" paramName="单位地址" paramType="string(0,-1)" paramValue="dwdz"/>
                    <outParam ignoreNull="1" paramCode="dwfrdbxm" paramName="单位法人代表姓名" paramType="string(0,-1)" paramValue="dwfrdbxm"/>
                    <outParam ignoreNull="1" paramCode="dwfrdbzjlx" paramName="单位法人代表证件类型" paramType="string(0,-1)" paramValue="dwfrdbzjlx"/>
                    <outParam ignoreNull="1" paramCode="dwfrdbzjhm" paramName="单位法人代表证件号码" paramType="string(0,-1)" paramValue="dwfrdbzjhm"/>
                    <outParam ignoreNull="1" paramCode="dwfrlxdh" paramName="单位法人联系电话" paramType="string(0,-1)" paramValue="dwfrlxdh"/>
                    <outParam ignoreNull="1" paramCode="dwsbzh" paramName="单位社保账号" paramType="string(0,-1)" paramValue="dwsbzh"/>
                    <outParam ignoreNull="1" paramCode="gszch" paramName="工商注册号" paramType="string(0,-1)" paramValue="gszch"/>
                    <outParam ignoreNull="1" paramCode="dwsshy" paramName="单位所属行业" paramType="string(0,-1)" paramValue="dwsshy"/>
                    <outParam ignoreNull="1" paramCode="dwxz" paramName="单位性质" paramType="string(0,-1)" paramValue="dwxz"/>
                    <outParam ignoreNull="1" paramCode="sbjczrs" paramName="社保缴存总人数" paramType="string(0,-1)" paramValue="sbjczrs"/>
                    <outParam ignoreNull="1" paramCode="sbjczjs" paramName="社保缴存总基数" paramType="string(0,-1)" paramValue="sbjczjs"/>
                    <outParam ignoreNull="1" paramCode="dwjb" paramName="单位级别" paramType="string(0,-1)" paramValue="dwjb"/>
                    <outParam ignoreNull="1" paramCode="sjdwmc" paramName="上级单位名称" paramType="string(0,-1)" paramValue="sjdwmc"/>
                    <outParam ignoreNull="1" paramCode="sjdwzh" paramName="上级单位账号" paramType="string(0,-1)" paramValue="sjdwzh"/>
                    <outParam ignoreNull="1" paramCode="dwlsgx" paramName="单位隶属关系" paramType="string(0,-1)" paramValue="dwlsgx"/>
                    <outParam ignoreNull="1" paramCode="dwjjlx" paramName="单位经济类型" paramType="string(0,-1)" paramValue="dwjjlx"/>
                    <outParam ignoreNull="1" paramCode="dwyb" paramName="单位邮编" paramType="string(0,-1)" paramValue="dwyb"/>
                    <outParam ignoreNull="1" paramCode="dwdzxx" paramName="单位电子信箱" paramType="string(0,-1)" paramValue="dwdzxx"/>
                    <outParam ignoreNull="1" paramCode="dwslrq" paramName="单位设立日期" paramType="string(0,-1)" paramValue="dwslrq"/>
                    <outParam ignoreNull="1" paramCode="dwfxr" paramName="单位发薪日" paramType="string(0,-1)" paramValue="dwfxr"/>
                    <outParam ignoreNull="1" paramCode="zgbm" paramName="主管部门" paramType="string(0,-1)" paramValue="zgbm"/>
                    <outParam ignoreNull="1" paramCode="sftsba" paramName="是否托收备案" paramType="string(0,-1)" paramValue="sftsba"/>
                    <outParam ignoreNull="1" paramCode="dwxxhdnf" paramName="单位信息核对年份" paramType="string(0,-1)" paramValue="dwxxhdnf"/>
                    <outParam ignoreNull="1" paramCode="szqy" paramName="所在区域" paramType="string(0,-1)" paramValue="szqy"/>
                    <outParam ignoreNull="1" paramCode="szxz" paramName="所在乡镇（街道）" paramType="string(0,-1)" paramValue="szxz"/>
                    <outParam ignoreNull="1" paramCode="yhmc" paramName="银行名称" paramType="string(0,-1)" paramValue="yhmc"/>
                    <outParam ignoreNull="1" paramCode="wdmc" paramName="网点名称" paramType="string(0,-1)" paramValue="wdmc"/>
                    <outParam ignoreNull="1" paramCode="jjr" paramName="缴交日" paramType="string(0,-1)" paramValue="jjr"/>
                    <outParam ignoreNull="1" paramCode="jcqsny" paramName="缴存起始年月" paramType="string(0,-1)" paramValue="jcqsny"/>
                    <outParam ignoreNull="1" paramCode="jzny" paramName="缴至年月" paramType="string(0,-1)" paramValue="jzny"/>
                    <outParam ignoreNull="1" paramCode="dwzhzt" paramName="单位账户状态" paramType="string(0,-1)" paramValue="dwzhzt"/>
                    <outParam ignoreNull="1" paramCode="dwhjzt" paramName="单位缓缴状态" paramType="string(0,-1)" paramValue="dwhjzt"/>
                    <outParam ignoreNull="1" paramCode="dwqjzt" paramName="单位欠缴状态" paramType="string(0,-1)" paramValue="dwqjzt"/>
                    <outParam ignoreNull="1" paramCode="yjrs" paramName="应缴人数" paramType="string(0,-1)" paramValue="yjrs"/>
                    <outParam ignoreNull="1" paramCode="yjje" paramName="应缴金额" paramType="string(0,-1)" paramValue="yjje"/>
                    <outParam ignoreNull="1" paramCode="zckye" paramName="暂存款余额" paramType="string(0,-1)" paramValue="zckye"/>
                    <outParam ignoreNull="1" paramCode="filename" paramName="经办人文件名" paramType="string(0,-1)" paramValue="filename"/>
                    <!--ish04新增-->
                    <outParam ignoreNull="1" paramCode="jbrxxjson" paramName="经办人信息json数据" paramType="string(0,-1)" paramValue="jbrxxjson"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/ln/TranTQHK01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranTQHK01" tranName="提前还款">
        <comps>
            <comp compCode="CompTQHK01" compName="获取提前还款后信息" expression="#flag=='hqtqhkhxx'">
            	<inParams>
            		<inParam paramCode="jkhtbh" ignoreNull="0" paramName="借款合同编号" paramValue="jkhtbh" paramType="string(1,30)"/>
            		<inParam paramCode="tqhkzje" ignoreNull="0" paramName="提前还款总金额" paramValue="tqhkzje" paramType="double(18,2)"/>
            		<inParam paramCode="dkbgbz" ignoreNull="0" paramName="贷款变更标志" paramValue="dkbgbz" paramType="string(1,2)"/>
					<inParam ignoreNull="1" paramCode="jkhtbhsz" paramName="借款合同编号数组" paramType="string(0,-1)" paramValue="jkhtbhsz"/>
					<inParam paramCode="hklx" ignoreNull="0" paramName="还款类型" paramValue="hklx" paramType="string(0,-1)"/>
				</inParams>
                <outParams>
                	<outParam ignoreNull="1" paramCode="shbj" paramName="实还本金" paramType="string(0,-1)" paramValue="shbj"/>
                	<outParam ignoreNull="1" paramCode="shfx" paramName="实还罚息" paramType="string(0,-1)" paramValue="shfx"/>
                	<outParam ignoreNull="1" paramCode="shlx" paramName="实还利息" paramType="string(0,-1)" paramValue="shlx"/>
                </outParams>
            </comp>
            <comp compCode="CompTQHK02" compName="提交提前还款信息" expression="#flag=='tjxx'">
            	<inParams>
            		<inParam paramCode="jkhtbh" ignoreNull="1" paramName="借款合同编号" paramValue="jkhtbh" paramType="string(1,30)"/>
            		<inParam paramCode="tqhkzje" ignoreNull="1" paramName="提前还款总金额" paramValue="tqhkzje" paramType="double(18,2)"/>
            		<inParam paramCode="dkbgbz" ignoreNull="1" paramName="dkbgbz" paramValue="dkbgbz" paramType="string(1,2)"/>
					<inParam ignoreNull="1" paramCode="jkhtbhsz" paramName="借款合同编号数组" paramType="string(0,-1)" paramValue="jkhtbhsz"/>
				</inParams>
            	<outParams>
                	<!--启用凭证系统时设置此出口参数  -->
               		<outParam ignoreNull="1" paramCode="filename" paramName="凭证文件名" paramType="string(0,-1)" paramValue="filename"/>
                </outParams>
            </comp>
            <comp compCode="CompTQHK03" compName="获取公积金还款人信息" expression="#flag=='hqgjjhkr'">
            	<inParams>
            		<inParam paramCode="jkhtbh" ignoreNull="0" paramName="借款合同编号" paramValue="jkhtbh" paramType="string(1,30)"/>
            		<inParam paramCode="instance" ignoreNull="0" paramName="实例号" paramValue="_IS" paramType="int"/>
					<inParam ignoreNull="1" paramCode="jkhtbhsz" paramName="借款合同编号数组" paramType="string(0,-1)" paramValue="jkhtbhsz"/>
				</inParams>
            </comp>
            <comp compCode="CompTQHK04" compName="根据月数获取提前还月供金额" expression="#flag=='hqtqhygje'">
            	<inParams>
            		<inParam paramCode="jkhtbh" ignoreNull="0" paramName="借款合同编号" paramValue="jkhtbh" paramType="string(1,30)"/>
            		<inParam paramCode="hygqs" ignoreNull="0" paramName="还月供期数" paramValue="hygqs" paramType="int"/>
					<inParam ignoreNull="1" paramCode="jkhtbhsz" paramName="借款合同编号数组" paramType="string(0,-1)" paramValue="jkhtbhsz"/>
				</inParams>
            	<outParams>
                	<outParam ignoreNull="1" paramCode="tqhkzje" paramName="提前还款总金额" paramType="string(0,-1)" paramValue="tqhkzje"/>
                </outParams>
            </comp>
        </comps>
    </tran>
</trans>

=== laoqianlaile/net-hall/src/main/java/trans/dw/TranCHDKTQ01.xml
<?xml version="1.0" encoding="UTF-8"?>
<trans xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../trans.xsd">
    <tran tranCode="TranCHDKTQ01" tranName="偿还公积金贷款提取提交">
        <comps>
            <comp compCode="CompCHDKTQ01" compName="偿还公积金贷款提取提交" expression="">
            	<inParams>
            		<inParam paramCode="tqyy" ignoreNull="0" paramName="提取原因" paramValue="tqyy" paramType="string(0,-1)"/>
            		<inParam paramCode="jkhtbh" ignoreNull="1" paramName="借款合同编号" paramValue="jkhtbh" paramType="string(0,-1)"/>
            		<inParam paramCode="sdhtbh" ignoreNull="1" paramName="商贷合同编号" paramValue="sdhtbh" paramType="string(0,-1)"/>
            		<inParam paramCode="wqhtbh" ignoreNull="1" paramName="网签合同编号" paramValue="wqhtbh" paramType="string(0,-1)"/>
            		<inParam paramCode="dkyh" ignoreNull="0" paramName="贷款银行" paramValue="dkyh" paramType="string(0,-1)"/>
            		<inParam paramCode="dkye" ignoreNull="0" paramName="贷款余额" paramValue="dkye" paramType="string(0,-1)"/>
            		<inParam paramCode="jsfs" ignoreNull="0" paramName="结算方式" paramValue="jsfs" paramType="string(0,-1)"/>
					<inParam paramCode="skrzhmc" ignoreNull="0" paramName="收款人账户名称" paramValue="skrzhmc" paramType="string(1,120)" />
					<inParam paramCode="skrkhyh" ignoreNull="0" paramName="收款人开户银行" paramValue="skrkhyh" paramType="string(1,20)" />
					<inParam paramCode="skrzhhm" ignoreNull="0" paramName="收款人账户号码" paramValue="skrzhhm" paramType="string(1,20)" />
					<inParam paramCode="hklx" ignoreNull="0" paramName="还款类型" paramValue="hklx" paramType="string(0,-1)"/>
            		<inParam paramCode="tqje" ignoreNull="0" paramName="提取金额" paramValue="tqje" paramType="string(0,-1)"/>
            		<inParam paramCode="jymm" ignoreNull="0" paramName="交易密码" paramValue="jymm" paramType="string(0,-1)"/>
            		<inParam paramCode="sjhm" ignoreNull="0" paramName="手机号码" paramValue="sjhm" paramType="string(0,11)"/>
					<inParam ignoreNull="1" paramCode="jkhtbhsz" paramName="借款合同编号数组" paramType="string(0,-1)" paramValue="jkhtbhsz"/>
				</inParams>
            </comp>
        </comps>
    </tran>
</trans>
